;;; monochrome-dark-theme.el --- Monochrome Dark -*- lexical-binding: t; -*-

;; An Emacs port of the VS Code theme `mikehhodgson.monochrome-dark`.
;;;###theme-autoload

;;; Use C-u C-x = (what-cursor-position with a prefix argument).
;;; This shows detailed text properties at point, including the face(s), without moving point to another buffer.

(deftheme monochrome-dark
  "Monochrome Dark theme ported from VS Code.")

(let* ((bg "#1f2123")
       (bg-alt "#17181a")
       (bg-dim "#101213")
       (bg-soft "#252729")
       (bg-region "#2e303e")
       (bg-diff-add "#9bb95533")
       (bg-diff-del "#ff000033")
       (bg-diff-hunk "#cccccc33")
       (fg "#d9dde1")
       (fg-strong "#ffffff")
       (fg-dim "#7f888d")
       (fg-faint "#666d73")
       (fg-muted "#575d62")
       (comment "#6a7075")
       (keyword "#e6e6e6")
       (string "#cfd3d7")
       (type "#dadfe4")
       (builtin "#d2d7db")
       (function "#e2e5e8")
       (constant "#d8dde1")
       (number "#b5bcc2")
       (variable "#dde2e6")
       (warning "#c8c8c8")
       (error "#ff5f5f")
       (success "#9bb955")
       (link "#d6dbe0")
       (selection "#2e303e")
       (cursor "#d9dde1")
       (border "#313334")
       (border-strong "#454547")


       (background "#1a1a1a")
       (border "#222426")
       (foreground "#ffffff")
       (cursor-bg "#ffffff")
       (cursor-fg "#222426")
       (selection "#606060")
       (line-highlight-background "#303030")
       (inactive-foreground "#aaaaaa")
       (mode-line-background "#000000")
       (string "#b3b3b3")
       (comment "#888888")
       (keyword "#969696")
       (git-deleted "#BB0000")
       (git-inserted "#0BB055")
       (git-inserted "#9BB055")
       (error "#FF0000")
       (warning "#FFFA00")
       )

  (custom-theme-set-variables
   'monochrome-dark
   `(ansi-color-names-vector
     [,bg-dim ,error ,success ,warning ,link ,builtin ,string ,fg]))

  (custom-theme-set-faces
   'monochrome-dark
   `(default ((t (:background ,background :foreground ,foreground))))
   `(cursor ((t (:background ,cursor-bg :foreground ,cursor-fg))))
   `(fringe ((t (:background ,background :foreground ,fg-dim))))
   `(region ((t (:background ,selection))))
   `(secondary-selection ((t (:background ,selection))))
   `(highlight ((t (:background ,bg-soft))))
   `(hl-line ((t (:background ,line-highlight-background))))
   `(shadow ((t (:foreground ,fg-faint))))
   `(link ((t (:foreground ,link :underline t))))
   `(link-visited ((t (:foreground ,builtin :underline t))))
   `(button ((t (:foreground ,link :underline t))))
   `(minibuffer-prompt ((t (:foreground ,fg-strong :weight bold))))
   `(escape-glyph ((t (:foreground ,builtin))))
   `(trailing-whitespace ((t (:background ,error))))
   `(vertical-border ((t (:foreground ,border))))
   `(window-divider ((t (:foreground ,border))))
   `(window-divider-first-pixel ((t (:foreground ,border))))
   `(window-divider-last-pixel ((t (:foreground ,border))))
   `(mode-line ((t (:background ,bg-dim :foreground ,fg :box nil))))
   `(mode-line-inactive ((t (:background ,bg-alt :foreground ,fg-muted :box nil))))
   `(mode-line-highlight ((t (:foreground ,fg-strong))))
   `(header-line ((t (:background ,bg-dim :foreground ,fg :box nil))))
   `(tab-line ((t (:background ,background :foreground ,fg-muted :box nil :underline nil))))
   `(tab-line-tab ((t (:background ,bg-alt :foreground ,fg :box nil))))
   `(tab-line-tab-current ((t (:background ,bg :foreground ,fg-strong :box nil :weight bold))))
   `(tab-line-tab-inactive ((t (:background ,bg-dim :foreground ,fg-muted :box nil))))
   `(tab-line-highlight ((t (:background ,bg-soft :foreground ,fg-strong))))
   `(line-number ((t (:background ,background :foreground ,fg-muted))))
   `(line-number-current-line ((t (:background ,bg :foreground ,fg-strong :weight bold))))
   `(completions-common-part ((t (:foreground ,fg-strong :weight bold))))
   `(completions-first-difference ((t (:foreground ,warning :weight bold))))
   `(match ((t (:background ,bg-soft :foreground ,fg-strong :weight bold))))
   `(isearch ((t (:background ,warning :foreground ,bg-dim :weight bold))))
   `(lazy-highlight ((t (:background ,bg-soft :foreground ,fg-strong))))
   `(show-paren-match ((t (:background ,fg-dim :foreground ,bg :weight bold))))
   `(show-paren-mismatch ((t (:background ,error :foreground ,bg-dim :weight bold))))
   `(success ((t (:foreground ,success :weight bold))))
   `(warning ((t (:foreground ,warning :weight bold))))
   `(error ((t (:foreground ,error :weight bold))))
   `(tooltip ((t (:background ,bg-soft :foreground ,fg))))
   `(widget-field ((t (:background ,bg-alt :foreground ,fg))))
   `(widget-button ((t (:foreground ,link :weight bold))))

   `(font-lock-builtin-face ((t (:foreground ,keyword))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,comment))))
   `(font-lock-comment-face ((t (:foreground ,comment :slant italic))))
   `(font-lock-constant-face ((t (:foreground ,keyword))))
   `(font-lock-doc-face ((t (:foreground ,comment :slant italic))))
   `(font-lock-function-name-face ((t (:foreground ,function))))
   `(font-lock-function-call-face ((t (:foreground ,fg))))
   `(font-lock-keyword-face ((t (:foreground ,keyword))))
   `(font-lock-negation-char-face ((t (:foreground ,keyword :weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground ,keyword))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,fg-strong :weight bold))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,fg-strong :weight bold))))
   `(font-lock-property-name-face ((t (:foreground ,variable))))
   `(font-lock-property-use-face ((t (:foreground ,variable))))
   `(font-lock-string-face ((t (:foreground ,string))))
   `(font-lock-type-face ((t (:foreground ,type))))
   `(font-lock-variable-name-face ((t (:foreground ,variable))))
   `(font-lock-variable-use-face ((t (:foreground ,variable))))
   `(font-lock-warning-face ((t (:foreground ,warning :weight bold))))
   `(font-lock-operator-face ((t (:foreground ,keyword))))

   `(tree-sitter-hl-face:attribute ((t (:foreground ,variable))))
   `(tree-sitter-hl-face:comment ((t (:foreground ,comment :slant italic))))
   `(tree-sitter-hl-face:constant ((t (:foreground ,constant))))
   `(tree-sitter-hl-face:constant.builtin ((t (:foreground ,builtin))))
   `(tree-sitter-hl-face:escape ((t (:foreground ,fg-strong :weight bold))))
   `(tree-sitter-hl-face:function ((t (:foreground ,function))))
   `(tree-sitter-hl-face:function.call ((t (:foreground ,function))))
   `(tree-sitter-hl-face:keyword ((t (:foreground ,keyword :weight bold))))
   `(tree-sitter-hl-face:method.call ((t (:foreground ,function))))
   `(tree-sitter-hl-face:operator ((t (:foreground ,keyword))))
   `(tree-sitter-hl-face:property ((t (:foreground ,variable))))
   `(tree-sitter-hl-face:property.definition ((t (:foreground ,variable))))
   `(tree-sitter-hl-face:punctuation ((t (:foreground ,fg-dim))))
   `(tree-sitter-hl-face:punctuation.bracket ((t (:foreground ,fg-dim))))
   `(tree-sitter-hl-face:punctuation.delimiter ((t (:foreground ,fg-dim))))
   `(tree-sitter-hl-face:punctuation.special ((t (:foreground ,fg-strong :weight bold))))
   `(tree-sitter-hl-face:string ((t (:foreground ,string))))
   `(tree-sitter-hl-face:string.special ((t (:foreground ,string))))
   `(tree-sitter-hl-face:tag ((t (:foreground ,function))))
   `(tree-sitter-hl-face:type ((t (:foreground ,type))))
   `(tree-sitter-hl-face:type.argument ((t (:foreground ,type))))
   `(tree-sitter-hl-face:variable ((t (:foreground ,variable))))
   `(tree-sitter-hl-face:variable.builtin ((t (:foreground ,builtin))))
   `(tree-sitter-hl-face:label ((t (:foreground ,warning))))

   `(typescript-ts-jsx-tag-face ((t (:foreground ,keyword))))
   `(typescript-ts-jsx-attribute-face ((t (:foreground ,constant))))

   `(diff-added ((t (:background ,bg-diff-add :foreground ,fg))))
   `(diff-changed ((t (:background ,bg-soft :foreground ,fg-dim))))
   `(diff-context ((t (:foreground ,fg-dim))))
   `(diff-file-header ((t (:background ,bg-dim :foreground ,fg-strong :weight bold))))
   `(diff-header ((t (:background ,bg-dim :foreground ,fg :weight bold))))
   `(diff-hunk-header ((t (:background ,bg-diff-hunk :foreground ,fg-strong :weight bold))))
   `(diff-removed ((t (:background ,bg-diff-del :foreground ,fg))))

   `(magit-section-heading ((t (:foreground ,fg-strong :weight bold))))
   `(magit-section-highlight ((t (:background ,bg-soft))))
   `(magit-branch-current ((t (:foreground ,fg-strong :weight bold))))
   `(magit-branch-local ((t (:foreground ,fg :weight bold))))
   `(magit-branch-remote ((t (:foreground ,fg-dim :weight bold))))
   `(magit-diff-added ((t (:background ,bg-diff-add :foreground ,fg))))
   `(magit-diff-added-highlight ((t (:background ,bg-diff-add :foreground ,fg-strong :weight bold))))
   `(magit-diff-removed ((t (:background ,bg-diff-del :foreground ,fg))))
   `(magit-diff-removed-highlight ((t (:background ,bg-diff-del :foreground ,fg-strong :weight bold))))
   `(magit-diff-context ((t (:foreground ,fg-dim))))
   `(magit-diff-context-highlight ((t (:background ,bg-soft :foreground ,fg))))
   `(magit-diff-hunk-heading ((t (:background ,bg-diff-hunk :foreground ,fg-strong :weight bold))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,bg-diff-hunk :foreground ,fg-strong :weight bold))))

   `(org-block ((t (:background ,bg-alt :foreground ,fg))))
   `(org-block-begin-line ((t (:background ,bg-dim :foreground ,fg-faint))))
   `(org-block-end-line ((t (:background ,bg-dim :foreground ,fg-faint))))
   `(org-code ((t (:foreground ,builtin))))
   `(org-document-title ((t (:foreground ,fg-strong :weight bold :height 1.2))))
   `(org-done ((t (:foreground ,success :weight bold))))
   `(org-drawer ((t (:foreground ,fg-faint))))
   `(org-level-1 ((t (:foreground ,fg-strong :weight bold :height 1.15))))
   `(org-level-2 ((t (:foreground ,fg :weight bold :height 1.1))))
   `(org-level-3 ((t (:foreground ,fg-dim :weight bold))))
   `(org-level-4 ((t (:foreground ,fg-strong :weight bold))))
   `(org-level-5 ((t (:foreground ,fg :weight bold))))
   `(org-level-6 ((t (:foreground ,fg-dim :weight bold))))
   `(org-level-7 ((t (:foreground ,fg :weight bold))))
   `(org-level-8 ((t (:foreground ,fg-dim :weight bold))))
   `(org-link ((t (:foreground ,link :underline t))))
   `(org-meta-line ((t (:foreground ,fg-faint))))
   `(org-special-keyword ((t (:foreground ,fg-faint))))
   `(org-table ((t (:foreground ,link))))
   `(org-todo ((t (:foreground ,error :weight bold))))
   `(org-verbatim ((t (:foreground ,string))))
   `(org-quote ((t (:foreground ,fg-faint :slant italic))))

   `(dired-directory ((t (:foreground ,fg-strong :weight bold))))
   `(dired-flagged ((t (:foreground ,error :weight bold))))
   `(dired-header ((t (:foreground ,fg-strong :weight bold))))
   `(dired-ignored ((t (:foreground ,fg-faint))))
   `(dired-mark ((t (:foreground ,fg-strong :weight bold))))
   `(dired-perm-write ((t (:foreground ,fg-dim))))
   `(dired-symlink ((t (:foreground ,fg :weight bold))))
   `(dired-warning ((t (:foreground ,error :weight bold))))

   `(treemacs-window-background-face ((t (:background ,bg-alt :foreground ,fg))))
   `(treemacs-hl-line-face ((t (:background ,line-highlight-background))))
   `(treemacs-directory-face ((t (:foreground ,foreground))))
   `(treemacs-directory-collapsed-face ((t (:foreground ,foreground))))
   `(treemacs-file-face ((t (:foreground ,fg))))
   `(treemacs-root-face ((t (:foreground ,fg-strong ;; :underline t
                                         :weight bold :height 1.2))))
   `(treemacs-root-unreadable-face ((t (:foreground ,fg-strong :underline t :strike-through t :weight bold :height 1.2))))
   `(treemacs-root-remote-face ((t (:foreground ,fg-strong :underline t :weight bold :height 1.2))))
   `(treemacs-root-remote-unreadable-face ((t (:foreground ,fg-strong :underline t :strike-through t :weight bold :height 1.2))))
   `(treemacs-root-remote-disconnected-face ((t (:foreground ,warning :underline t :weight bold :height 1.2))))
   `(treemacs-term-node-face ((t (:foreground ,fg-dim))))
   ;; `(treemacs-git-unmodified-face ((t (:foreground ,fg))))
   ;; `(treemacs-git-modified-face ((t (:foreground ,fg-strong))))
   ;; `(treemacs-git-renamed-face ((t (:foreground ,fg-dim :slant italic))))
   ;; `(treemacs-git-ignored-face ((t (:foreground ,fg-faint))))
   ;; `(treemacs-git-untracked-face ((t (:foreground ,fg))))
   ;; `(treemacs-git-added-face ((t (:foreground ,fg-strong))))
   ;; `(treemacs-git-conflict-face ((t (:foreground ,error :weight bold))))
   `(treemacs-tags-face ((t (:foreground ,fg-strong :weight bold))))
   `(treemacs-help-title-face ((t (:foreground ,fg-strong :weight bold))))
   `(treemacs-help-column-face ((t (:foreground ,fg-strong :underline t))))
   `(treemacs-on-failure-pulse-face ((t (:foreground ,bg-dim :background ,error :extend t))))
   `(treemacs-on-success-pulse-face ((t (:foreground ,bg-dim :background ,success :extend t))))
   `(treemacs-fringe-indicator-face ((t (:foreground ,cursor))))
   `(treemacs-header-button-face ((t (:foreground ,fg-strong :weight bold))))
   `(treemacs-peek-mode-indicator-face ((t (:background ,bg-soft))))
   `(treemacs-marked-file-face ((t (:foreground ,fg-strong :background ,bg-region :weight bold))))
   ;; `(treemacs-git-commit-diff-face ((t (:foreground ,fg-faint :slant italic))))
   `(treemacs-async-loading-face ((t (:foreground ,fg-faint :height 0.8))))
   `(treemacs-nerd-icons-root-face ((t (:foreground ,fg-strong))))
   `(treemacs-nerd-icons-file-face ((t (:foreground ,fg-dim))))

   `(eglot-highlight-symbol-face ((t (:background "#000000" ;:weight bold
                     ;;                             :underline (:color "#ffffff")
                                                  :box (:line-width (-1 . -1) :color "#ffffff")
;;       :box (:line-width 1 :color "#ffffff")
))))

   `(eglot-inlay-hint-face ((t (:foreground ,fg-faint :slant italic))))
   `(eglot-parameter-hint-face ((t (:foreground ,fg-faint :slant italic))))
   `(eglot-type-hint-face ((t (:foreground ,fg-faint :slant italic))))
   `(eglot-diagnostic-tag-deprecated-face ((t (:inherit shadow :strike-through t))))
   `(eglot-diagnostic-tag-unnecessary-face ((t (:inherit shadow :slant italic))))

   `(company-tooltip ((t (:background ,bg-alt :foreground ,fg))))
   `(company-tooltip-selection ((t (:background ,bg-region :foreground ,fg-strong))))
   `(company-tooltip-common ((t (:foreground ,fg-strong :weight bold))))
   `(company-scrollbar-bg ((t (:background ,bg-dim))))
   `(company-scrollbar-fg ((t (:background ,bg-soft))))
   `(company-tooltip-annotation ((t (:foreground ,fg-faint))))

   `(which-func ((t (:foreground ,fg-strong :weight bold))))
   `(whitespace-space ((t (:background ,bg :foreground ,bg-soft))))
   `(whitespace-tab ((t (:background ,bg :foreground ,bg-soft))))
   `(whitespace-trailing ((t (:background ,error))))
   `(rainbow-delimiters-depth-1-face ((t (:foreground ,fg-dim))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,fg))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,fg-dim))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,fg-strong))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,fg))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,fg-dim))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,error :weight bold))))
   `(paren-face-match ((t (:background ,bg-soft :foreground ,fg-strong :weight bold))))
   `(paren-face-mismatch ((t (:background ,error :foreground ,bg-dim :weight bold))))
   `(paren-face-no-match ((t (:background ,error :foreground ,bg-dim :weight bold))))
   ))


(font-lock-add-keywords
 nil
 '(("[(){}\\[\\]]" . font-lock-keyword-face)))

(font-lock-flush)
(font-lock-ensure)

(provide-theme 'monochrome-dark)

;;; monochrome-dark-theme.el ends here
