# https://github.com/mpv-player/mpv/blob/master/etc/mpv.conf

# Start in fullscreen mode by default.
fs=yes

# https://superuser.com/questions/1581867/how-to-infinite-loop-every-video-i-play-as-defaut-on-mpv-player-without-having-t
#loop-file=inf
# just loop the playlist by default
loop-playlist=inf
