general {
    lock_cmd = omarchy-system-lock                         # lock screen and 1password
#    before_sleep_cmd = OMARCHY_LOCK_ONLY=true omarchy-system-lock    # lock before suspend without scheduling display off.
    before_sleep_cmd = OMARCHY_LOCK_ONLY=true omarchy-system-lock; rm -f ~/.local/state/omarchy/toggles/idle-off; pkill -RTMIN+9 waybar           # lock before suspend. ensure idle lock re-enabled
    after_sleep_cmd = sleep 1 && omarchy-system-wake                 # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3                                      # wait until screen is locked
}

# Start screensaver after 2.5 minutes
listener {
    timeout = 150
#    on-timeout = pidof hyprlock || omarchy-launch-screensaver
    on-timeout = pidof hyprlock || ~/.local/bin/omarchy-idle-guard omarchy-launch-screensaver
}

# Lock system after 5 minutes (screensaver resets idle timer, so have to just do half + 2s margin)
listener {
    timeout = 152
#    on-timeout = omarchy-system-lock
    on-timeout = ~/.local/bin/omarchy-idle-guard omarchy-system-lock # lock screen when timeout has passed
    on-resume = omarchy-system-wake
}
