# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  kb_layout = us
  # kb_options = compose:caps # ,grp:alts_toggle
  kb_options = caps:ctrl_shifted_capslock # compose:caps # ,grp:alts_toggle

  # Change speed of keyboard repeat
  #repeat_rate = 40
  #repeat_delay = 600
  #repeat_rate = 60     # Fast key repeat for coding
  #repeat_delay = 200   # Short delay for responsiveness
  repeat_rate = 50
  repeat_delay = 400

  # sensitivity = 1
  accel_profile = flat

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitivity for mouse/trackpad (default: 0)
  #sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4

    # Enable the touchpad while typing
    disable_while_typing = true

    # Left-click-and-drag with three fingers
    drag_3fg = 1

    # Resize window with touchpad
    #bindm = SUPER, ALT_L, resizewindow # interfered with SUPER, ALT_L, F
    # bindm = SUPER, SHIFT_L, resizewindow # doesn't work at all though
  }
}
device {
  # trackpad specific settings
  name = synaptics-tm2438-005
  sensitivity = 1
  #accel_profile = adaptive
}

# Scroll nicely in the terminal
windowrule = match:class (Alacritty|kitty|foot), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2

#windowrule = border_color rgb(00ff00), match:class gnucash
windowrule = no_screen_share on, match:class gnucash

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
gesture = 4, horizontal, workspace

gesture = 4, up, fullscreen
gesture = 4, down, float

# tried to get nautilus nav working but didn't work
# https://forum.hypr.land/t/2-finger-swipe-for-back-forward/1133
#gesture = 2, left, dispatcher, exec, nautilus -k XF86Forward
#gesture = 2, right, dispatcher, exec, nautilus -k XF86Back

#gesture = 2, left, mod: SUPER, exec, nautilus --back
#gesture = 2, right, mod: SUPER, exec, nautilus --forward
