# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
# env = GDK_SCALE,2
# monitor=,preferred,auto,auto

# Good compromise for 27" or 32" 4K monitors (but fractional!)
# env = GDK_SCALE,1.75
# monitor=,preferred,auto,1.6

# Straight 1x setup for low-resolution displays like 1080p or 1440p
env = GDK_SCALE,1
monitor=,preferred,auto,1

# Example for Framework 13 w/ 6K XDR Apple display
# monitor = DP-5, 6016x3384@60, auto, 2
# monitor = eDP-1, 2880x1920@120, auto, 2

# https://wiki.hypr.land/Configuring/Tearing/
#general {
#    allow_tearing = true
#}
#
#windowrule = match:class cs2, immediate yes

windowrule = match:class osgViewer, immediate yes

windowrule {
  name = ecwolf
  match:class = ecwolf

  content = game
  immediate = yes
  fullscreen = on
}

windowrule {
  name = Kerbal Space Program
#  match:title = Kerbal Space Program
   match:class = steam_app_220200

  content = game
  immediate = yes
  fullscreen = on
}

# windowrule {
#   name = gnucash
#   match:initial_title = ^GnuCash$

#   float = on
#   center = on
#   size = 5rd00 400
#   no_initial_focus = on
# }

# float and focus save as dialog
windowrule {
  name = saveas
  match:class = xdg-desktop-portal-gtk

  focus_on_activate = on
  #stay_focused = on # can't focus overwrite dialog as original dialog keeps focus
  float = on
}

input {
  # prevent dialogs from losing focus if mouse wasn't originally over them
  mouse_refocus = false
}


# display flicker troubleshoot:
cursor {
    no_hardware_cursors = true
}
misc {
    vrr = 0
}